[pytest]
DJANGO_SETTINGS_MODULE = core.dev_settings
python_files = tests.py test_*.py *_tests.py
testpaths = tests
addopts = 
    --cov=app
    --cov-report=html
    --cov-report=term-missing
    --strict-markers
    -v

markers =
    unit: Unit tests
    integration: Integration tests
    e2e: End-to-end tests
