# Generated by Django 5.2.4 on 2025-10-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="outfitsearch",
            name="color",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="outfitsearch",
            name="fit",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="outfitsearch",
            name="gender",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="outfitsearch",
            name="outfit_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="outfitsearch",
            name="style_summary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
