# Generated by Django 5.2.4 on 2026-06-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_outfitsearch_refined_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="outfitsearch",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
